<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <!-- Code analysis (added to every project) -->
    <PackageVersion Include="Reihitsu.Analyzer" Version="0.21.0" />

    <!-- Runtime -->
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />

    <!-- Test -->
    <PackageVersion Include="MSTest" Version="4.2.3" />
  </ItemGroup>

</Project>
