<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\GlobalSuppressions.cs" Link="GlobalSuppressions.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlexToJellyfinSync.Core\PlexToJellyfinSync.Core.csproj" />
    <ProjectReference Include="..\PlexToJellyfinSync.Data\PlexToJellyfinSync.Data.csproj" />
    <ProjectReference Include="..\PlexToJellyfinSync.Service\PlexToJellyfinSync.Service.csproj" />
  </ItemGroup>

</Project>
